FROM node:20

WORKDIR /usr/src/app

# Instalar OpenSSL y dependencias necesarias
RUN apt-get update && apt-get install -y openssl

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3017